// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth from "./routes/api/auth.ts";
import * as $callback from "./routes/callback.ts";
import * as $index from "./routes/index.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth.ts": $api_auth,
    "./routes/callback.ts": $callback,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
